# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1a2a6ba0bfc5364ffc4bd8720d19c0f949937a47d3b3ab647bcdb39a04f338271bdf96af5c713c2a33e86ec626c162d03542b966074b3b0be3de48914901631

test:
  secret_key_base: 07f5cd6e9d511de0b68ec90f6ab3725fee5485e1ecaa3d872bf19ba5f6234e76c651444d4f3146665bec70a7f4f545908191210a77352a6745ad292db72998d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
